const SELECTED_FORMAT = "selectedFormat";
const FORMATTED_DATE = "YYYY/MM/DD";
const NEXT = "NEXT";
const MINUTE_INTERVAL_ARRAY = [1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60];

export { SELECTED_FORMAT, FORMATTED_DATE, NEXT, MINUTE_INTERVAL_ARRAY };
